Validates content type

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -70,6 +70,18 @@ jobs:
           path: main
           submodules: recursive
 
+      - name: Hide sensitive inputs
+        uses: levibostian/action-hide-sensitive-inputs@v1
+
+      - name: Validate IPA URL
+        run: |
+          response=$(curl -sI "${{ inputs.ipa_url }}")
+          content_type=$(echo "$response" | grep -i "Content-Type" | awk '{print $2}' | tr -d '\r')
+          if [[ "$content_type" != "application/octet-stream" ]]; then
+            echo "Direct link to the IPA file required. Entered link is not a direct download or does not point to an IPA file."
+            exit 1
+          fi
+
       - name: Install Dependencies
         run: brew install make ldid
 
@@ -114,9 +126,6 @@ jobs:
         run: |
           deb_url="https://github.com/dayanch96/YTLite/releases/download/v${{ inputs.tweak_version }}/com.dvntm.ytlite_${{ inputs.tweak_version }}_iphoneos-arm.deb"
           wget "$deb_url" --no-verbose -O ${{ github.workspace }}/ytplus.deb
-
-      - name: Hide sensitive inputs
-        uses: levibostian/action-hide-sensitive-inputs@v1
 
       - name: Download YouTube
         id: download_youtube
diff --git a/.github/workflows/ytp_beta.yml b/.github/workflows/ytp_beta.yml
--- a/.github/workflows/ytp_beta.yml
+++ b/.github/workflows/ytp_beta.yml
@@ -70,6 +70,27 @@ jobs:
           path: main
           submodules: recursive
 
+      - name: Hide sensitive inputs
+        uses: levibostian/action-hide-sensitive-inputs@v1
+
+      - name: Validate IPA URL
+        run: |
+          response=$(curl -sI "${{ inputs.ipa_url }}")
+          content_type=$(echo "$response" | grep -i "Content-Type" | awk '{print $2}' | tr -d '\r')
+          if [[ "$content_type" != "application/octet-stream" ]]; then
+            echo "Direct link to the IPA file required. Entered link is not a direct download or does not point to an IPA file."
+            exit 1
+          fi
+
+      - name: Validate Tweak URL
+        run: |
+          response=$(curl -sI "${{ inputs.tweak_url }}")
+          content_type=$(echo "$response" | grep -i "Content-Type" | awk '{print $2}' | tr -d '\r')
+          if [[ "$content_type" != "application/octet-stream" ]]; then
+            echo "Direct link to the tweak file required. Entered link is not a direct download or does not point to a DEB file."
+            exit 1
+          fi
+
       - name: Install Dependencies
         run: brew install make ldid
 
@@ -108,9 +129,6 @@ jobs:
 
       - name: Install cyan
         run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
-
-      - name: Hide sensitive inputs
-        uses: levibostian/action-hide-sensitive-inputs@v1
 
       - name: Download YouTube
         id: download_youtube
